# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFil():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()

  
  def test_fil(self):
    self.driver.get("https://app.neapro.site/login")
    self.driver.set_window_size(1050, 840)
    self.driver.find_element(By.XPATH, "//*[@id='__layout']/div/section/div[2]/div/div/div/form/div[1]/div[1]/div/input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("dmdmfilatov@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("Admin71257")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(5)
  

    self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu").move_to_element()
    self.driver.find_element(By.CSS_SELECTOR, ".avatar_link_name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".popup_banner_close").click()
    self.driver.find_element(By.LINK_TEXT, "Безопасность и вход").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .name").click()
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("+7(999) 999-9999")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".img > img").click()
    self.driver.find_element(By.LINK_TEXT, "Документы").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(1) .document-tile:nth-child(1) > img").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Справка.jpg").click()
    self.vars["win7359"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(1) .document-tile:nth-child(2)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Справка.jpg").click()
    self.vars["win7814"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win7814"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(1) > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(2)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Скачать").click()
    self.vars["win1503"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1503"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".document-tile:nth-child(3)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Скачать").click()
    self.vars["win6245"] = self.wait_for_window(2000)
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.LINK_TEXT, "Диплом и сертификат").click()
    self.driver.switch_to.window(self.vars["win6245"])
    self.driver.switch_to.window(self.vars["root"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .link_name").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .link_name").click()
    self.driver.find_element(By.LINK_TEXT, "Домашнее задание").click()
    self.driver.find_element(By.LINK_TEXT, "Материалы").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".logout_name").click()
  
